CREATE TABLE IF NOT EXISTS quotes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  industry VARCHAR(50) DEFAULT '',
  work_types TEXT,
  contracting_types TEXT,
  business_characteristics TEXT,
  email VARCHAR(255) DEFAULT '',
  first_name VARCHAR(100) DEFAULT '',
  last_name VARCHAR(100) DEFAULT '',
  phone VARCHAR(50) DEFAULT '',
  business_name VARCHAR(255) DEFAULT '',
  address VARCHAR(255) DEFAULT '',
  state VARCHAR(50) DEFAULT '',
  car_year VARCHAR(10) DEFAULT '',
  car_make VARCHAR(100) DEFAULT '',
  car_model VARCHAR(100) DEFAULT '',
  car_trim VARCHAR(100) DEFAULT '',
  car_use VARCHAR(100) DEFAULT '',
  car_daily_miles VARCHAR(50) DEFAULT '',
  car_ownership VARCHAR(50) DEFAULT '',
  car_full_coverage VARCHAR(50) DEFAULT '',
  status ENUM('new','reviewed','follow-up') DEFAULT 'new',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
